### ISSUE TITLE
Install plugin compression filters

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/datacontainer#10]
Setup some plugin compression filters and create a snapshot with filters + regular setup.

Filters to include:

 * SZIP (is this already installed?)
 * LZF (this installed with h5py - anything else we need to do?)
 * BLOSC
 * MAFISC

Any others we should include?

**Comment by hyoklee** [comment]
Anacoda default:
```
        I/O filters (external): deflate(zlib)
```

**Comment by hyoklee** [comment]
Where do you want to install hdf5, python, and h5py with custom filters?

**Comment by jreadey** [comment]
We already have hdf5, python, and h5py installed.  Isn't adding a customer filter a matter of build the filter and making sure the shared object is found in the right place?

**Comment by hyoklee** [comment]
I don't know. I haven't tried any custom filter. Have you?

**Comment by jreadey** [comment]
No and our documentation doesn't seem that helpful.  Elena should be able to point you to what you need to know.

**Comment by hyoklee** [comment]
Blosc is not supported by h5py. 

https://github.com/h5py/h5py/issues/611

**Comment by jreadey** [comment]
What  @andrewcollette is saying is that there's no customized support for Blosc in h5py.  It should be possible to use h5py with the Blosc compressor as long as the environment is setup correctly.  h5py has an api with a generic filter interface which should be adequate.  Anyway, we don't need to create datasets using Blosc with h5py, just read them.

**Comment by hyoklee** [comment]
@jreadey I spent some time yesterday with filters but blosc did not work like mafisc worked with h5py. That's why I was asking @aldanor in https://github.com/Blosc/hdf5-blosc/issues/6#issuecomment-155244039.

What do you mean by "just read them"? Do you have sample HDF5 data files in blosc compression that I should test with h5py?

**Comment by jreadey** [comment]
@hyoklee - I was thinking we could use repack to compress the existing datasets.  Does repack work with plugin filters?

**Comment by jreadey** [comment]
@hyoklee - any update on this?

**Comment by hyoklee** [comment]
@jreadey Do you want me to repack NCEP data with szip and mafisc? I did not hear anything from blosc developer.

**Comment by hyoklee** [comment]
The current snapshot with szip/mafisc  is 'joe_issue10'. However, zmq is broken in this snapshot so it can't be used as ipcontroller.

**Comment by jreadey** [comment]
Yes, do szip and mafisc.

Once you update the files, we can fix the snapshots to handle the compressor and zmq.

**Comment by hyoklee** [comment]
How about chunking size? Both h5py & unidata algorithms?

**Comment by jreadey** [comment]
Have we seen any difference with the different chunk layouts?  If not I'd just choose one.

**Comment by hyoklee** [comment]
Szip-compressed data are now available at s3://hdfdata/ncep3_chunk_45_180_szip_8_NN/.
It took 22 hours.

**Comment by jreadey** [comment]
How about checking in the script (to datacontainer/util) used to do the conversion so that we've documented how the compression was done?

**Comment by hyoklee** [comment]
I checked in here: https://github.com/HDFGroup/datacontainer/commit/ecfbb23dbd457b2d23886e24d7abceee79f0aa90

**Comment by jreadey** [comment]
Nice!

**Comment by hyoklee** [comment]
Mafisc-compressed data are now available at s3://hdfdata/ncep3_chunk_45_180_mafisc_32002_1_0/.
It also took 22 hours.

**Comment by hyoklee** [comment]
I finally hacked blosc filters and started generating repacked data here:
s3://hdfdata/ncep3_chunk_45_180_blosc_2_2_4/

I'll close ticket when repacking is done.

**Comment by ajelenak-thg** [comment]
Great job @hyoklee! The details of that hacking should be captured somewhere...

**Comment by jreadey** [comment]
What type of compression are we getting with Mafisc?

**Comment by hyoklee** [comment]
@ajelenak-thg It's captured in my blog: https://confluence.hdfgroup.org/display/~hyoklee/2015/11/18/How+to+make+Blosc+filter+work+with+HDF5
@jreadey What do you mean by "type"?  Are you talking about disk space savings in terms of ratio?

**Comment by jreadey** [comment]
right

**Comment by hyoklee** [comment]
@jreadey Here are s3cmd du results:

```
17659481823 7775 objects s3://hdfdata/ncep3_chunk_45_180_mafisc_32002_1_0/
47881067158 7850 objects s3://hdfdata/ncep3_chunk_45_180_gzip_9/
130575759722 15700 objects s3://hdfdata/ncep3/
```

**Comment by jreadey** [comment]
Looks like it's ~1:4 compression.  It will be interesting to see if the output differs at all.

**Comment by hyoklee** [comment]
Repacking with blosc compression took 4h 40min. Image used for this task is now called "issue10."

**Comment by catawbasam** [comment]
```@ajelenak-thg It's captured in my blog: https://confluence.hdfgroup.org/display/~hyoklee/2015/11/18/How+to+make+Blosc+filter+work+with+HDF5```

I get a login prompt at this URL.  Any chance of making this publicly available?

**Comment by jreadey** [comment]
@hyoklee - how about you copy the confluence post to the docs file in the repo?

**Comment by jreadey** [comment]
@catawbasam - I've add the setup instructions here.

**Comment by ajelenak-thg** [comment]
> I've add the setup instructions here.

@jreadey Where? There is no link.

**Comment by ajelenak-thg** [comment]
@jreadey Found the link, edited your orig. comment. Fixed.

**Comment by jreadey** [comment]
Thanks.

**Comment by catawbasam** [comment]
thanks!
