### ISSUE TITLE
lib/chunking.py  doesn't work for 2d dataset.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/datacontainer#16]
```
>>> chunking.unidata_chunk([720, 1440])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/datacontainer/lib/chunking.py", line 65, in unidata\
_chunk
    raise ValueError('Variable shape must be 3-dimensional: %s' % varSha\
pe)
ValueError: Variable shape must be 3-dimensional: [720, 1440]
>>> 
```

**Comment by ajelenak-thg** [comment]
Unidata's chunking formula only works for 3d datasets.

**Comment by hyoklee** [comment]
So what chunk size should I use for NCEP under Unidata algorithm case?

**Comment by ajelenak-thg** [comment]
The Unidata formula does not apply unless a dataset is 3d. You could assign the value of 1 to an imaginary third dimension, for example: shape (720, 1440) becomes (1, 720, 1440).

If we start collating data from more than one NCEP file that would effectively produce 3d datasets and the Unidata formula could be applied. For the sake of experiment, lets assume we collate all the data for one dataset from all NCEP files. What would its shape be? I would then use both Unidata and h5py formulas to see the suggested chunk sizes. Then we could discuss whether it's worthwhile to "tile up" several of these chunks into one new file.

**Comment by hyoklee** [comment]
OK. It returned [1, 22, 46] so I'll use 22,46.
