### ISSUE TITLE
zmq error?

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/datacontainer#19]
If I run 
```
$ ipcontroller --ip=*
```
I get the following message:
```
ImportError: /home/ubuntu/anaconda/envs/py34/lib/python3.4/site-packages/zmq/backend/cython/message.cpython-34m.so: undefined symbol: zmq_msg_gets
```
How can I solve this problem?

**Comment by ajelenak-thg** [comment]
What snapshot did you use for that VM?

**Comment by hyoklee** [comment]
Does it matter? I think user guide should add instruction on how to install everything from scratch Ubuntu.

**Comment by hyoklee** [comment]
On issue10 snapshot, another weird zmq error occurs:

```
(py34)ubuntu@test2:~/datacontainer/filters$ python summary.py ncep_100.txt 
ImportError: /home/ubuntu/anaconda/envs/py34/lib/python3.4/site-packages/zm\
q/backend/cython/message.cpython-34m.so: undefined symbol: zmq_msg_gets
```

**Comment by jreadey** [comment]
I'm not sure what is up with the ZMQ error.  I merged @hyoklee's updates to the snapshot10 snapshot.
