### ISSUE TITLE
Download cortad dataset

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/datacontainer#2]
Download Version5 from here: http://data.nodc.noaa.gov/cortad/Version5/.
Store in s3:://hdfdata/cortad on Griffin.

**Comment by ajelenak-thg** [comment]
Tried this and here's the error:
```
Invoked as: /home/ubuntu/s3cmd/s3cmd -c /home/ubuntu/s3test.cfg -v put cortadv5_FilledSST.nc s3://hdfdata/cortad/
Problem: error: [Errno 104] Connection reset by peer
S3cmd:   1.6.0+
python:   2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:50:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/home/ubuntu/s3cmd/s3cmd", line 2813, in <module>
    rc = main()
  File "/home/ubuntu/s3cmd/s3cmd", line 2721, in main
    rc = cmd_func(args)
  File "/home/ubuntu/s3cmd/s3cmd", line 384, in cmd_object_put
    response = s3.object_put(full_name, uri_final, extra_headers, extra_label = seq_label)
  File "/home/ubuntu/s3cmd/S3/S3.py", line 600, in object_put
    return self.send_file_multipart(file, headers, uri, size)
  File "/home/ubuntu/s3cmd/S3/S3.py", line 1303, in send_file_multipart
    upload = MultiPartUpload(self, file, uri, headers)
  File "/home/ubuntu/s3cmd/S3/MultiPart.py", line 25, in __init__
    self.upload_id = self.initiate_multipart_upload()
  File "/home/ubuntu/s3cmd/S3/MultiPart.py", line 72, in initiate_multipart_upload
    response = self.s3.send_request(request)
  File "/home/ubuntu/s3cmd/S3/S3.py", line 1072, in send_request
    http_response = conn.c.getresponse()
  File "/home/ubuntu/anaconda/envs/py27/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/home/ubuntu/anaconda/envs/py27/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/home/ubuntu/anaconda/envs/py27/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/ubuntu/anaconda/envs/py27/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
```

This is the "get cortad files" script:
```bash
#!/usr/bin/env bash

export no_proxy="griffin-objstore.opensciencedatacloud.org"
function with_proxy() {
    PROXY="http://cloud-proxy:3128"
    http_proxy="${PROXY}" https_proxy="${PROXY}" ftp_proxy="${PROXY}" $@
}

with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_FilledSST.nc
s3cmd put  cortadv5_FilledSST.nc s3://hdfdata/cortad/
rm cortadv5_FilledSST.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_HarmonicsClimatology.nc
s3cmd put  cortadv5_HarmonicsClimatology.nc s3://hdfdata/cortad/
rm cortadv5_HarmonicsClimatology.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_MedfillSST.nc
s3cmd put  cortadv5_MedfillSST.nc s3://hdfdata/cortad/
rm cortadv5_MedfillSST.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_SSTA.nc
s3cmd put  cortadv5_SSTA.nc s3://hdfdata/cortad/
rm cortadv5_SSTA.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_SeaIceFraction.nc
s3cmd put  cortadv5_SeaIceFraction.nc s3://hdfdata/cortad/
rm cortadv5_SeaIceFraction.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_TSA.nc
s3cmd put  cortadv5_TSA.nc s3://hdfdata/cortad/
rm cortadv5_TSA.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_WeeklySST.nc
s3cmd put  cortadv5_WeeklySST.nc s3://hdfdata/cortad/
rm cortadv5_WeeklySST.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_WindSpeed.nc
s3cmd put  cortadv5_WindSpeed.nc s3://hdfdata/cortad/
rm cortadv5_WindSpeed.nc
```

Questions:

1. Am I using the `s3cmd` correctly?

1. Are there any storage quotas on the S3 storage or file size?

**Comment by jreadey** [comment]
Try it now – I think they were having some object store outage earlier today.

John

From: Aleksandar Jelenak
Reply-To: HDFGroup/datacontainer
Date: Monday, October 19, 2015 at 11:53 AM
To: HDFGroup/datacontainer
Cc: John Readey
Subject: Re: [datacontainer] Download cortad dataset (#2)


Tried this and here's the error:

Invoked as: /home/ubuntu/s3cmd/s3cmd -c /home/ubuntu/s3test.cfg -v put cortadv5_FilledSST.nc s3://hdfdata/cortad/
Problem: error: [Errno 104] Connection reset by peer
S3cmd:   1.6.0+
python:   2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:50:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/home/ubuntu/s3cmd/s3cmd", line 2813, in <module>
    rc = main()
  File "/home/ubuntu/s3cmd/s3cmd", line 2721, in main
    rc = cmd_func(args)
  File "/home/ubuntu/s3cmd/s3cmd", line 384, in cmd_object_put
    response = s3.object_put(full_name, uri_final, extra_headers, extra_label = seq_label)
  File "/home/ubuntu/s3cmd/S3/S3.py", line 600, in object_put
    return self.send_file_multipart(file, headers, uri, size)
  File "/home/ubuntu/s3cmd/S3/S3.py", line 1303, in send_file_multipart
    upload = MultiPartUpload(self, file, uri, headers)
  File "/home/ubuntu/s3cmd/S3/MultiPart.py", line 25, in __init__
    self.upload_id = self.initiate_multipart_upload()
  File "/home/ubuntu/s3cmd/S3/MultiPart.py", line 72, in initiate_multipart_upload
    response = self.s3.send_request(request)
  File "/home/ubuntu/s3cmd/S3/S3.py", line 1072, in send_request
    http_response = conn.c.getresponse()
  File "/home/ubuntu/anaconda/envs/py27/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/home/ubuntu/anaconda/envs/py27/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/home/ubuntu/anaconda/envs/py27/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/ubuntu/anaconda/envs/py27/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer


This is the "get cortad files" script:

#!/usr/bin/env bashexport no_proxy="griffin-objstore.opensciencedatacloud.org"function with_proxy() {
    PROXY="http://cloud-proxy:3128"
    http_proxy="${PROXY}" https_proxy="${PROXY}" ftp_proxy="${PROXY}" $@
}

with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_FilledSST.nc
s3cmd put  cortadv5_FilledSST.nc s3://hdfdata/cortad/
rm cortadv5_FilledSST.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_HarmonicsClimatology.nc
s3cmd put  cortadv5_HarmonicsClimatology.nc s3://hdfdata/cortad/
rm cortadv5_HarmonicsClimatology.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_MedfillSST.nc
s3cmd put  cortadv5_MedfillSST.nc s3://hdfdata/cortad/
rm cortadv5_MedfillSST.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_SSTA.nc
s3cmd put  cortadv5_SSTA.nc s3://hdfdata/cortad/
rm cortadv5_SSTA.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_SeaIceFraction.nc
s3cmd put  cortadv5_SeaIceFraction.nc s3://hdfdata/cortad/
rm cortadv5_SeaIceFraction.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_TSA.nc
s3cmd put  cortadv5_TSA.nc s3://hdfdata/cortad/
rm cortadv5_TSA.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_WeeklySST.nc
s3cmd put  cortadv5_WeeklySST.nc s3://hdfdata/cortad/
rm cortadv5_WeeklySST.nc
with_proxy wget ftp://ftp.nodc.noaa.gov/pub/data.nodc/cortad/Version5/cortadv5_WindSpeed.nc
s3cmd put  cortadv5_WindSpeed.nc s3://hdfdata/cortad/
rm cortadv5_WindSpeed.nc

Questions:

  1.  Am I using the s3cmd correctly?

  2.  Are there any storage quotas on the S3 storage or file size?

**Comment by ajelenak-thg** [comment]
Nope, still the same.

**Comment by jreadey** [comment]
I've opened an issue with OSDC on this.  I'll post here when I get an update.

**Comment by jreadey** [comment]
I never heard back on the ticket, but it looks to be working now.

**Comment by ajelenak-thg** [comment]
Done: `s3cmd ls s3://hdfdata/cortad/`.

**Comment by jreadey** [comment]
It is actually downloaded now!
