### ISSUE TITLE
Not an HDF5 file error occurs for summary.py in cluster mode.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/datacontainer#24]
I don't think parallel testing works on OSDC because I/O is not reliable. Is there any way to make test fail-proof against I/O error?

```
 File "/home/ubuntu/anaconda/envs/py34/lib/python3.4/site-packages/ipyparall\
el/error.py", line 231, in collect_exceptions
    raise CompositeError(msg, elist)
ipyparallel.error.CompositeError: one or more exceptions from call to method:\
 processFiles
[0:apply]: OSError: Not an HDF5 file: /home/ubuntu/s3/hdfdata/ncep3_chunk_45_\
180_gzip_9/GSSTF_NCEP.3.1987.07.01.he5
```

The file is a valid HDF-EOS5 file:
```
py34)ubuntu@ipcontroller:~$ s3cmd get s3://hdfdata/ncep3_chunk_45_180_gzip_9\
/GSSTF_NCEP.3.1987.07.01.he5
's3://hdfdata/ncep3_chunk_45_180_gzip_9/GSSTF_NCEP.3.1987.07.01.he5' -> './GS\
STF_NCEP.3.1987.07.01.he5'  [1 of 1]
's3://hdfdata/ncep3_chunk_45_180_gzip_9/GSSTF_NCEP.3.1987.07.01.he5' -> './GS\
STF_NCEP.3.1987.07.01.he5'  [1 of 1]
 5999068 of 5999068   100% in    0s     7.65 MB/s  done
(py34)ubuntu@ipcontroller:~$ h5dump GSSTF_NCEP.3.1987.07.01.he5 
HDF5 "GSSTF_NCEP.3.1987.07.01.he5" {
GROUP "/" {
   GROUP "HDFEOS" {
      GROUP "ADDITIONAL" {
         GROUP "FILE_ATTRIBUTES" {
```

**Comment by hyoklee** [comment]
This happened when '--c 86' argument was passed to summary.py.

**Comment by jreadey** [comment]
I'll work on some retry logic in the s3download class.

**Comment by ajelenak-thg** [comment]
I had the same problem over the weekend. Don't know why or how to fix it for now.

**Comment by jreadey** [comment]
if you run it twice it seems to work. i.e.

$ python summary.py --input <filelist> --path <path> -c 1
  >some random exceptions but most files are downloaded
$ python summary.py --input <filelist> --path <path> -c 1
  > files that didn't make it the first time get downloaded.  Files already present are not re-downloaded.
$ python summary.py --input <filelist> --path <path> -c 1
  > really cooking now!

**Comment by hyoklee** [comment]
Yes. I got the result on second time.

**Comment by jreadey** [comment]
We want to separate out the time used for download vs. computation time.
