### ISSUE TITLE
Add PyDAP for iPython parallel engines.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/datacontainer#34]
It will be handy for Hyrax testing.

**Comment by jreadey** [comment]
There's no official py3.4 build for PyDap.
hyoklee@, can you try out this PR and see if it works for us: https://github.com/robertodealmeida/pydap/pull/9?

**Comment by hyoklee** [comment]
@jreadey Haven't you already integrated PyDAP for Python3 so that HDF Compass can work with Python 3?

**Comment by jreadey** [comment]
No, Compass is using Python 2.7.  But that came up in the discussion of moving Compass to Py3.

**Comment by hyoklee** [comment]
I tried the branch but I get the following error:

```
(py34)ubuntu@issue32:~/src/issue32$ python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    dataset = open_url(file_path)
  File "/home/ubuntu/anaconda/envs/py34/lib/python3.4/site-packages/Pydap-3.2-p\
y3.4.egg/pydap/client.py", line 58, in open_url
    dataset = DAPHandler(url).dataset
  File "/home/ubuntu/anaconda/envs/py34/lib/python3.4/site-packages/Pydap-3.2-p\
y3.4.egg/pydap/handlers/dap.py", line 52, in __init__
    dds = r.text.decode('ascii')
AttributeError: 'str' object has no attribute 'decode'

```

**Comment by hyoklee** [comment]
I created a snapshot called "issue34" that contains PyDAP. Can @jreadey restart ipengines with this image and run https://github.com/HDFGroup/datacontainer/blob/master/filters/summary_hyrax.py in parallel?
